#!/usr/bin/env zsh

############
# TERMINAL #
############
alias aliases='code ~/dotfiles/mixins/aliases'
alias zshreload='source ~/.zshrc'

alias lc='colorls --gs --sd -lA'
alias lcc='colorls --gs --sd --tree'

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'


##########
# FINDER #
##########

alias f='open -a Finder ./' # Also aliased to 'ofd' from osx plugin

alias dotfiles='cd $HOME/dotfiles/'
alias dropbox='cd $HOME/Dropbox/'
alias sites='cd $HOME/Sites/'

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

trash () { command mv "$@" ~/.Trash ; }    # trash:        Moves a file to the MacOS trash
ql () { qlmanage -p "$*" >& /dev/null; }   # ql:           Opens any file in MacOS Quicklook Preview


##############
# NETWORKING #
##############

# IP addresses
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"
alias ping='ping -c 5'      # Pings with 5 packets, not unlimited


###########
# VARIOUS #
###########

alias at='open -a "Atom"'

# Get week number
alias week='date +%V'

# Stuff I never really use but cannot delete either because of http://xkcd.com/530/
alias stfu="osascript -e 'set volume output muted true'"
alias pumpitup="osascript -e 'set volume output volume 100'"

# Disk space
alias df='df -h'            # Disk free, in gigabytes, not bytes
alias du='du -h -c'         # Calculate total disk usage for a folder

# Kill all the tabs in Chrome to free up memory
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

#   ii:  display useful host related informaton
ii() {
  print -P "\nYou are logged on $FG[003]$HOST"
  print -P "\nAdditionnal information:$reset_color " ; uname -a
  print -P "\n$FG[003]Users logged on:$reset_color " ; w -h
  print -P "\n$FG[003]Current date:$reset_color " ; date
  print -P "\n$FG[003]Machine stats:$reset_color " ; uptime
  print -P "\n$FG[003]Current network location:$reset_color " ; scselect
  print -P "\n$FG[003]Public facing IP Address:$reset_color " ; myip
  print -P "\n$FG[003]Local IP Address:$reset_color "; localip
  print -P "\n$FG[003]DNS Configuration:$reset_color " ; scutil --dns | sed -ne '/resolver #1/,$ p' | head -n +6
  print
}

# Dictionary search, prefix ^ to get only words starting letters. ex: ^wh
dict() {
    grep "$@" /usr/share/dict/words
}

###############
# DEVELOPMENT #
###############

alias npmlist='npm list -g --depth=0'
alias npmlist1='npm list -g --depth=1'


#######
# AGR #
#######

# AGR 5
export agr5dir=~/Sites/agr5/agr5-client
export agr5root=~/Sites/agr5
alias agr5='cd ~/Sites/agr5'
alias serve5='cd $agr5root; npm run me -- serve'
alias test5='cd $agr5root; gulp coverage:auto'
alias e2e5='cd $agr5root; npm run me -- e2e-run -v'

# Backend
alias me='cd $agr5root; npm run me -- '
alias build='cd $agr5root; me bd-dev-nav2009 && run-forecast && backup-db'
alias build-bm='cd $agr5root; me bd-dev-bm && run-forecast && backup-db'
alias build-forecast='cd $agr5root; npm run me -- deploy-forecast-svc'
alias build-api='cd $agr5root; me build-web-api'
alias debug-api='cd $agr5root; me dev-debug-api'
alias install-db='cd $agr5root; me build-dev-sql-nav2009'
alias restore-db='cd $agr5root; me dev-restore-prod-db'
alias run-forecast='cd $agr5root; me db-run-forecasts'
alias stop-forecast='cd $agr5root; me undeploy-forecast-svc'
alias start-forecast='cd $agr5root: me deploy-forecast-svc'
alias backup-db='cd $agr5root; me dev-backup-prod-db'
alias clean-all='cd $agr5root; me cleanbuild-dotnet && me cleanbuild-sql && me cleanbuild-web-client'
alias log='cd $agr5root; cd log; open -t `ls -1t | head -1`' # open the most recently modified log file

# AGR 6
export agr6root=~/Sites/agr6
alias agr6='cd $agr6root'
alias serve='cd $agr6root; ng serve'
alias test='cd $agr6root; npm run test'
alias lint='cd $agr6root; ng lint'
alias buildprod='cd $agr6root; ng build --prod'

alias e2e='cd $agr6root; npm run e2e-no-serve'
alias e2e+='e2e && stop-forecast && restore-db && start-forecast'
alias e2ec='stop-forecast && restore-db && start-forecast'