#!/usr/bin/env zsh

alias zshreload='source ~/.zshrc'

alias lc='colorls --gs --sd -lA'
alias lcc='colorls --gs --sd --tree'

alias f='open -a Finder ./' # Also aliased to 'ofd' from osx plugin

# Folder shortcuts
alias dotfiles='cd $HOME/dotfiles/'
alias dropbox='cd $HOME/Dropbox/'
alias sites='cd $HOME/Sites/'

# ALIASES FROM: https://github.com/mathiasbynens/dotfiles/blob/master/.aliases

# Get week number
alias week='date +%V'

# Update installed Ruby gems, npm, and their installed packages
# Use 'bubu' from brew plugin to update brew
alias npmu='npm install npm -g; npm update -g'
alias gemu='gem update --system; gem update; gem cleanup'

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Stuff I never really use but cannot delete either because of http://xkcd.com/530/
alias stfu="osascript -e 'set volume output muted true'"
alias pumpitup="osascript -e 'set volume output volume 100'"

# Kill all the tabs in Chrome to free up memory
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'


# ALIASES FROM: https://gist.github.com/natelandau/10654137

trash () { command mv "$@" ~/.Trash ; }    # trash:        Moves a file to the MacOS trash
ql () { qlmanage -p "$*" >& /dev/null; }   # ql:           Opens any file in MacOS Quicklook Preview
alias DT='tee ~/Desktop/terminalOut.txt'   # DT:           Pipe content to file on MacOS Desktop


# ALIASES FROM: https://github.com/mathiasbynens/dotfiles/blob/master/.aliases

# IP addresses
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

#   ii:  display useful host related informaton
#   -------------------------------------------------------------------
ii() {
  print -P "\nYou are logged on $FG[003]$HOST"
  print -P "\nAdditionnal information:$reset_color " ; uname -a
  print -P "\n$FG[003]Users logged on:$reset_color " ; w -h
  print -P "\n$FG[003]Current date:$reset_color " ; date
  print -P "\n$FG[003]Machine stats:$reset_color " ; uptime
  print -P "\n$FG[003]Current network location:$reset_color " ; scselect
  print -P "\n$FG[003]Public facing IP Address:$reset_color " ; myip
  print -P "\n$FG[003]Local IP Address:$reset_color "; localip
  print -P "\n$FG[003]DNS Configuration:$reset_color " ; scutil --dns | sed -ne '/resolver #1/,$ p' | head -n +6
  print
}

# ALIASES FROM: https://justin.abrah.ms/dotfiles/zsh.html
alias ping='ping -c 5'      # Pings with 5 packets, not unlimited
alias df='df -h'            # Disk free, in gigabytes, not bytes
alias du='du -h -c'         # Calculate total disk usage for a folder

# Dictionary search, prefix ^ to get only words starting letters. ex: ^wh
dict() {
    grep "$@" /usr/share/dict/words
}
